### ISSUE TITLE
Automatically registering components or systems by reading annotations

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/geary#1]
We currently need to register all subclasses of the base component interface for kotlinx.serialization. Similarly systems need to be registered to run.

- Instead, we should be able to annotate our components and systems to automatically register them all in one place.
- This should likely be done at runtime and not compile time since we don't want to increase compile time for other projects using this api.
- It may be worth passing a plugin class reference in each annotation. Realistically if two plugins register components with the same serial names there will be issues anyways, but it's useful information to have anyways if we'd like to, say reload only a specific plugin.

I don't know the correct way to do this kind of annotation processing at runtime, feel free to leave suggestions below.

**Comment by Derongan** [comment]
I don't think this really makes sense.

If we do it at runtime, we basically have to either scan the entire jar for any geary extension once it is loaded. This is expensive and reflection heavy.

I think that its much simpler to make them register the components themselves, or to provide a convenient (optional) compile time processor.
