### ISSUE TITLE
Engines should provide a check for if an entity is present, at least in tests

### ISSUE THREAD

**Issue by Derongan** [MineInAbyss/geary#52]
I noticed in your code you do some hacky stuff by using Geary.getNextId to figure out if an entity has been removed. This is downright barbaric. It only makes sense if we assume that the engine always uses the lowest free slot for the next entity. You are relying on a hidden implementation detail in tests.

Additionally the use of Engine vs the constructed engine is really confusing and smelly.

**Comment by 0ffz** [comment]
Sorry can you elaborate on what you were trying to do originally?

The constructed engine stuff is just using spigots service system unless I'm missing the point ur making there too.

**Comment by Derongan** [comment]
This is probably 2 bugs.

1. Geary Engine should provide a method to check if a GearyEntityId is tracked by the engine. There are a number of tests that test for Entity removal that end up being very hacky because of lack of support for this feature. You instead grab the next available entity id and check to see if it is the slot that was associated with the deleted entity.

2. The use of `Engine` rather than directly using implementation under test in geary tests is problematic. If we are testing the geary engine, we should not be creating it then relying on the service getter to fetch the engine during the test. We have a direct reference to the engine already. See `QueryManagerTest` for an example.

**Comment by 0ffz** [comment]
Added `Entity.exists()` [example test usage](https://github.com/MineInAbyss/geary/blob/9ae475ab28247f646e79426a0e4eafaa521ee28a/geary-core/src/jvmTest/kotlin/com/mineinabyss/geary/datatypes/GearyEntityTests.kt#L153)
